### ISSUE TITLE
Lead Form Page Creation

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#19]
Prework: 
- [x] confirm with Clayton if this is a page or a modal

If Page:
- [x] create and design page inline with rest of site design
Note: you may need to get imagery approval from Clayton and have it made by Faith
- [x] mimic other freeland site copy to create contact page copy (theres no copy on other freeland sites' contact pages)
- [x] insert form (this may be an existing one or a separate one you have to create)
- [x] Fix styling on submit button

**Comment by salegre** [comment]
## Added Styling for Submit Button and Other Form Elements
- Lines 30-44 on styles.css

**Comment by lapinell** [comment]
Looks great - few more things
- [x] space between sections
- [x] h2 needs to match rest of site
