### ISSUE TITLE
VDP Template

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#2]
Issue card needs more detail.

- [x] Add Button to Fleet Form
- [x] Add purchase process explanation under buttons
- [x] Add image carousel
- [x] Styling buttons

**Comment by lapinell** [comment]
## Add Button to Fleet Form
- edited divi-freeland-child/functions.php lines 30-33 & 48
- added button linking to /contact/ page

**Comment by salegre** [comment]
## Added Purchase Process Explanation structure
- edited **divi-freeland-child/functions.php** **lines 36-39 & 51**
- added structure in functions.php to allow for the copy for the purchase process explanation

**Comment by salegre** [comment]
## Add Image Carousel 
- added through plugin **"Product Gallery Slider for Woocommerce"**
- changes overflowing product images from a grid to a slider

**Comment by salegre** [comment]
## Styled the buttons defined in functions.php for the single product page
- edited **divi-freeland-child/style.css lines 17-28**
- matching the theme

**Comment by lapinell** [comment]
Approved minus one detail: Please fix either the text size of the buttons so they match and don't wrap in mobile, or something similar so the text doesn't wrap in mobile.

**Comment by lapinell** [comment]
Removing the wrap task in review and approving. Creating a new ticket for the buttons because it is more in depth than originally thought.
