### ISSUE TITLE
Vehicle Detail Page - Button Linking

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#22]
AC:
- [x] Change Form button verbiage to Inquire About  This Vehicle
- [x] Change Form button color to green (branded green)
- [x] Link Form button to Fleet Form Page
- [x] Change Vehicle Detail button verbiage to "Additional Vehicle Details"
- [x] Change VD button color to black
- [x] Link VD button to specific query search on corresponding WorkTruckSolutions site

**Comment by salegre** [comment]
## Settings for this can be found in All Import > Manage Import > Edit Import
