### ISSUE TITLE
List Template Modification

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#3]
- [x] List format instead of Grid
- [x] Mobile List Format

[Mockup](https://drive.google.com/file/d/0B9rbEX35gjWBRngzSE5JRnhESFBiNFlxa2x4WHY0amszR2xz/view?usp=sharing)

**Comment by lapinell** [comment]
## Name of Task within Issue

- file(s) that you edited with lines
- brief explanation to why

**Comment by lapinell** [comment]
## List Format Instead of Grid
- achieved with List/Grid plugin
- styling will be in the child theme style.css for both mobile and desktop

**Comment by lapinell** [comment]
- Grid achieved by creating child theme woocommerce templates:
   - archive-product.php
   -  content-product.php
- Uninstalled List/Grid plugin bc didn't need it; it was faster to code it into the theme and achieved higher quality results
- Styling still needed:
   - [x] when the title is longer and wraps the images shrinks and the detail wrapper grows.... weird
   - [x] the struckthrough price is bigger than the sale price
   - [x] add short description hook to achrive-page
   - [ ] Then do ALL of it again to the archive category page

**Comment by salegre** [comment]
Reviewed and left change requests @lapinell
