### ISSUE TITLE
Secondary footer on info page only

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#30]
# Acceptance Criteria
- [x] create a new global section according to the mockup [found here](https://drive.google.com/file/d/1Fruo6QXQwbKKVz1AYWkjpPz4_loBgTeI/view?usp=sharing)
- [x] leave out the buttons and links
- [x] place the new section on each info page above the reviews

**Comment by salegre** [comment]
- [x]  Put columns in boxes
