### ISSUE TITLE
Fix Search Button Which Is Not Working

### ISSUE THREAD

**Issue by salegre** [Media-Tree-Productions/freelandchildtheme#42]

**Comment by claytonglasser** [comment]
Currently there is some kind of extra erroneous on the box. 

![image](https://user-images.githubusercontent.com/3128577/73580330-c6b15300-444a-11ea-856a-532d0efa0bfb.png)

**Comment by lapinell** [comment]
Fix was within the Search setting under the plugin settings -- ajax search and search result page
