### ISSUE TITLE
fix footer blank spot

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#49]

**Comment by salegre** [comment]
## Text to Add
**Join The Freeland Family!**
Freeland is very proud to be recognized as Middle Tennessee’s largest full-service Fleet & Commercial dealership, serving customers in the greater Nashville metro area and beyond, so we’ve created Freeland Trucks to prove it! Whether you’re looking to purchase your first work truck, or an entire fleet of work trucks and cargo vans, our goal is to provide you and your business with unmatched inventory, competitive pricing, and world-class service before, during, and after your purchase. After all, our business is designed to support yours. Let’s get started!

**Comment by salegre** [comment]
## Added previous content back up
