### ISSUE TITLE
More vehicle details page CTA on VDP open in new tab

### ISSUE THREAD

**Issue by claytonglasser** [Media-Tree-Productions/freelandchildtheme#51]
https://github.com/Media-Tree-Productions/freelandchildtheme/pull/63

**Comment by salegre** [comment]
## Couldn't do with CSS or with Front-end settings. 

- [x] Need to look into how to change that from the WPAllImport Plugin.

**Comment by salegre** [comment]
Actionable solution modifying woo-commerce template.

**Comment by salegre** [comment]
## Fixed by adding target="_blank" to form
**Branch: #63** 
Line 22 of external.php
