### ISSUE TITLE
Change Freeland Trucks Sales number to 615-581-1698

### ISSUE THREAD

**Issue by claytonglasser** [Media-Tree-Productions/freelandchildtheme#77]

**Comment by lapinell** [comment]
Obstacle: This may be bigger than anticipated depending on the stakeholder needs.

To change the phone number on each inventory item, the number must be changed in the child theme files and then one must re-import the inventory. This is fine if the phone number rarely changes.

**Comment by claytonglasser** [comment]
Phone number will change rarely. Inventory is updated daily right?

**Comment by lapinell** [comment]
As of today, it is not. But it will be.
