### ISSUE TITLE
Menu tweaks

### ISSUE THREAD

**Issue by claytonglasser** [Media-Tree-Productions/freelandchildtheme#89]
-Default blue links (active state) needs color change
-Menu width increased, menu item text line height decreased

**Comment by claytonglasser** [comment]
This bit of CSS provides an override to prevent the menu items from breaking to a new line as often. 

#top-menu li li a {
    padding: 5px 5px !important;
}

**Comment by lapinell** [comment]
See pull request for code review linked above
