### ISSUE TITLE
Updated Videos for Staff

### ISSUE THREAD

**Issue by lapinell** [Media-Tree-Productions/freelandchildtheme#94]
Videos: https://drive.google.com/drive/folders/1LoVwf7Y4C54VsYYzbaeJ_lKpeD8W9yyg

**Comment by claytonglasser** [comment]
Greg Beier
https://vimeo.com/391535729  

Bill Rodgers
https://vimeo.com/391365088  

Al Woods
https://vimeo.com/391365247  

Tim Kohler
https://vimeo.com/391364553  

Kirk Lucas (Finance)
https://vimeo.com/391364676  

Howard Lange
https://vimeo.com/391364782 

 Herb Odem (Government contact)
 https://vimeo.com/391364876

Renae Wilson
https://vimeo.com/391364992 

Linda Golderg
https://vimeo.com/391543953 

Evan Diehl
https://vimeo.com/391539042

**Comment by lapinell** [comment]
Videos are already up within the vimeo links provided previously (supposedly after talking to Cameron)

**Comment by lapinell** [comment]
Cameron is reviewing
